import { Fragment } from 'react'

export default function PrivacyPolicy() {
  return (
    <Fragment>
      <div className='relative' id='home'>
        <div className='max-w-7xl pt-20 mx-auto px-6 mt-10 md:px-12 xl:px-6'>
          <div className='relative ml-auto'>
            <div className='lg:w-2/3 mx-auto'>
              <label className='block text-center'>
                <h1 className='text-4xl font-bold tracking-tight mb-2 text-gray-900'>
                  Privacy Policy
                </h1>
              </label>
              1. Introduction
Welcome to KG Jobs ("we", "our", or "us"). We operate https://www.jobs.kejanigarage.com (hereinafter referred to as the "Website"). This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Website and the choices you have associated with that data.

2. Definitions
SERVICE means the https://www.jobs.kejanigarage.com website operated by KG Jobs.
PERSONAL DATA means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).
USAGE DATA is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
COOKIES are small files stored on your device (computer or mobile device).
DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal person who processes the data on behalf of KG Jobs. We may use the services of various Service Providers in order to process your data more effectively.
DATA SUBJECT is any living individual who is the subject of Personal Data.
THE USER is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.
3. Data Collection and Use
We collect several different types of information for various purposes to provide and improve our Website for you.

Information You Provide to Us: We collect information that you voluntarily provide in the following ways: (a) Account Creation (b) Filling in a form on our site (c) Contacting us (d) Purchasing a plan (e) Inviting others to use KG Jobs

Information we collect automatically when you use our Services: (a) Log data such as errors, warnings, and usage of the service (b) Cookies (c) Analytics

Information we collect from other sources: (a) Payment Processors. In general, when you purchase one of our plans, your payment card information is provided directly to our third-party payment processor, Lemon Squeezy, and KG Jobs does not collect or store that information. However, we may receive limited information about your payment card from Lemon Squeezy, such as the last four digits of your card, the country of issuance, and the expiration date.

(b)Third-Party Services. Our Platform allows customers to integrate Third-Party services on the Platform. Once enabled, the provider of a Third-Party service may share certain information with KG Jobs such as email address and user name associated with that customer on the Third-Party Service as well as additional information that the provider has chosen to make available to KG Jobs to facilitate the integration. Customers should check the privacy settings and privacy policies of these Third-Party Services to understand what information may be shared with KG Jobs.

(C) Third Party Authentication Providers. KG Jobs allows you to sign up and log in to our Platform using third-party authentication providers such as Google. If you choose to sign up and log in in this manner, the third-party authentication service will ask your permission to share certain information with us, including your name, profile picture, and email address. You can control the information that we receive from third-party authentication providers using the privacy settings in your accounts with those services.

4. Types of Data Collected
Personal Data: While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to: Email address, Name, Address, and Phone number.
Usage Data: We may also collect information on how the Website is accessed and used. This may include information such as your computer's IP address, browser type, browser version, and other diagnostic data.
Tracking Cookies Data: We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information. Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service. Examples of Cookies we use: (a)Session Cookies: We use Session Cookies to operate our Service. (b) **Preference Cookies:**We use Preference Cookies to remember your preferences and various settings. (c) **Security Cookies:**We use Security Cookies for security purposes. (d) **Advertising Cookies:**Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.
5. Use of Data
KG Jobs uses the collected data for various purposes: (a) to provide and maintain our Service; (b) to notify you about changes to our Service; (c) to allow you to participate in interactive features of our Service when you choose to do so; (d) to provide customer support; (e) to gather analysis or valuable information so that we can improve our Service; (f) to monitor the usage of our Service; (g) to detect, prevent and address technical issues; (h) to fulfill any other purpose for which you provide it; (i) to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection; (j) to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.; (k) to provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information; (l) in any other way we may describe when you provide the information; (m) for any other purpose with your consent.

6. Retention of Data
We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies. We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.

7. Transfer of Data
Your information, including personal data, may be transferred to computers located outside of your state or country where data protection laws may differ. Your consent to this Privacy Policy represents your agreement to such transfers.

If you are located outside the United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to the United States and process it there.

Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.

KG Jobs will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.

8. Disclosure of Data
We may disclose your personal data in the good faith belief that such action is necessary to:

Comply with a legal obligation
Protect the personal safety of users of the Website or the public
Protect against legal liability
Business Transaction. If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.

Other cases. We may disclose your information also: (i) to our subsidiaries and affiliates; (ii) to contractors, service providers, and other third parties we use to support our business; (iii) to fulfill the purpose for which you provide it; (iv) for the purpose of including your company’s logo on our website; (v) for any other purpose disclosed by us when you provide the information.

9. Security of Data
The security of your data is important to us, but no method of transmission over the Internet or electronic storage is 100% secure. We strive to use commercially acceptable means to protect your personal data but cannot guarantee its absolute security.

10. Analytics
Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.

For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: https://policies.google.com/privacy?hl=en.

We also encourage you to review the Google’s policy for safeguarding your data: https://support.google.com/analytics/answer/6004245.

11. Payments
We may provide paid products and/or services within Service. In that case, we use third-party services for payment processing (e.g. payment processors).

We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.

12. Links to Other Sites
Our Service may contain links to other sites that are not operated by us. If you click a third-party link, you will be directed to that third-party’s site. We strongly advise you to review the Privacy Policy of every site you visit.

We have no control over and assume no responsibility for the content, privacy policies or practices of any third-party sites or services.

14. Changes to This Privacy Policy
We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.

We will inform you via email and/or a prominent notice on our Service before the change becomes effective and update the “effective date” at the top of this Privacy Policy.

You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when posted on this page.

15. Contact Us
If you have any questions about this Privacy Policy, please contact us:

By email: garagekejani@gmail.com
KG Jobs
            </div>
          </div>
        </div>
      </div>
    </Fragment>
  )
}
