import React, { useState } from 'react';
import Head from 'next/head'
import axios from 'axios'
import styles from '../styles/Home.module.css'
import { Axios } from 'axios';



const Home = () => {
  const [modifiedData, setModifiedData] = useState({
    ro: '',
    spec: '',
    fil: '',
    afte: ''
  });

  const [jobs, setJobs] = useState([])

  const handleChange = ({ target: { name, value } }) => {
    setModifiedData(prev => ({
      ...prev,
      [name]: value,
    }));
  };

  const handleSubmit = async e => {
    e.preventDefault();

    try {
      const response = await axios.post('http://127.0.0.1:5000/api/v1/search', {
        ...modifiedData
      });
      setJobs(response.data)
      console.log(response);
    } catch (error) {
      console.log(error);
    }
  };

  const job = jobs.map(j => (
    <tr key={jobs[j]}>
      <td>{j.role}</td>
      <td>{j.summary}</td>
      <td>{j.job_date}</td>
      <td>
        <a href={j.url} target="_blank" rel="noreferrer"><button>Visit Job</button></a>
      </td>
    </tr>
  )) 
  return (
    <>
      <Head>
        <title>Jobs Scrapper - Kejani Garage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h2>Kejani Garage Jobs Scrapper</h2>
        <form onSubmit={handleSubmit}>
          <label>
            Role:
            <input
              type='text'
              name='description'
              value=''
              onChange={handleChange}
            />
          </label>
          <label>
            Speciality:
            <input
              type='text'
              name='description'
              value=''
              onChange={handleChange}
            />
          </label>
          <label>
            Filter Out:
            <input
              type='text'
              name='description'
              value=''
              onChange={handleChange}
            />
          </label>
          <label>
            Before/After this date:
            <input
              type='text'
              name='description'
              value=''
              onChange={handleChange}
            />
          </label>
          <br />
          <button type="submit">Submit</button>
        </form>
        <table>
          <tr>
            <th>Role</th>
            <th>Summary</th>
            <th>Date</th>
            <th>{}</th>
          </tr>
          {job}
        </table>
      </main>
    </>
  )
  }

export default Home;
